package com.example.composestarter.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * 固定的应用配色。
 *
 * 这里不用 Android 12+ 的「动态取色」（Material You）：那样每台设备的颜色都跟着
 * 自己的壁纸走，同一份界面在不同机器上长得不一样。下面这套值是**从真机上读出来的
 * 动态配色**（Redmi K80 / HyperOS 3 / Android 16，2026-09-21 用 `dynamicLightColorScheme`
 * / `dynamicDarkColorScheme` 逐个角色打日志导出），把它写死之后所有设备都是同一套颜色，
 * 也不再受「换壁纸就换色」影响。
 *
 * 角色名和 Material 3 的 `ColorScheme` 一一对应，`Light` / `Dark` 分别对应浅色与深色模式。
 */

// ---- 浅色模式 ----
val LightPrimary = Color(0xFF3E6188)
val LightOnPrimary = Color(0xFFF7F9FF)
val LightPrimaryContainer = Color(0xFFACCFFC)
val LightOnPrimaryContainer = Color(0xFF21466B)
val LightInversePrimary = Color(0xFFAFC9EB)
val LightSecondary = Color(0xFF546071)
val LightOnSecondary = Color(0xFFF7F9FF)
val LightSecondaryContainer = Color(0xFFD7E3F8)
val LightOnSecondaryContainer = Color(0xFF465363)
val LightTertiary = Color(0xFF615A84)
val LightOnTertiary = Color(0xFFFCF7FF)
val LightTertiaryContainer = Color(0xFFD5CBFC)
val LightOnTertiaryContainer = Color(0xFF49426A)
val LightBackground = Color(0xFFF9F9FE)
val LightOnBackground = Color(0xFF2E333A)
val LightSurface = Color(0xFFF9F9FE)
val LightOnSurface = Color(0xFF2E333A)
val LightSurfaceVariant = Color(0xFFDEE2EC)
val LightOnSurfaceVariant = Color(0xFF5A5F67)
val LightSurfaceTint = Color(0xFF3E6188)
val LightInverseSurface = Color(0xFF0C0E12)
val LightInverseOnSurface = Color(0xFFE1E5EF)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)
val LightOutline = Color(0xFF767B83)
val LightOutlineVariant = Color(0xFFAEB2BB)
val LightScrim = Color(0xFF000000)
val LightSurfaceBright = Color(0xFFF9F9FE)
val LightSurfaceDim = Color(0xFFD6DAE3)
val LightSurfaceContainer = Color(0xFFEBEEF5)
val LightSurfaceContainerHigh = Color(0xFFE5E8F0)
val LightSurfaceContainerHighest = Color(0xFFDEE2EC)
val LightSurfaceContainerLow = Color(0xFFF2F3FA)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightPrimaryFixed = Color(0xFFACCFFC)
val LightPrimaryFixedDim = Color(0xFF9EC1ED)
val LightOnPrimaryFixed = Color(0xFF053256)
val LightOnPrimaryFixedVariant = Color(0xFF2B4F75)
val LightSecondaryFixed = Color(0xFFD7E3F8)
val LightSecondaryFixedDim = Color(0xFFC9D5E9)
val LightOnSecondaryFixed = Color(0xFF344050)
val LightOnSecondaryFixedVariant = Color(0xFF505C6D)
val LightTertiaryFixed = Color(0xFFD5CBFC)
val LightTertiaryFixedDim = Color(0xFFC7BEEE)
val LightOnTertiaryFixed = Color(0xFF352F56)
val LightOnTertiaryFixedVariant = Color(0xFF524B74)

// ---- 深色模式（同一套壁纸的深色变体）----
val DarkPrimary = Color(0xFFAFC9EB)
val DarkOnPrimary = Color(0xFF28425E)
val DarkPrimaryContainer = Color(0xFF3B5472)
val DarkOnPrimaryContainer = Color(0xFFD3E5FF)
val DarkInversePrimary = Color(0xFF3E6188)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF354151)
val DarkSecondaryContainer = Color(0xFF303C4C)
val DarkOnSecondaryContainer = Color(0xFFB3C0D4)
val DarkTertiary = Color(0xFFE3DBFF)
val DarkOnTertiary = Color(0xFF524B74)
val DarkTertiaryContainer = Color(0xFFD5CBFC)
val DarkOnTertiaryContainer = Color(0xFF49426A)
val DarkBackground = Color(0xFF0C0E12)
val DarkOnBackground = Color(0xFFE1E5EF)
val DarkSurface = Color(0xFF0C0E12)
val DarkOnSurface = Color(0xFFE1E5EF)
val DarkSurfaceVariant = Color(0xFF21262D)
val DarkOnSurfaceVariant = Color(0xFFA7ABB4)
val DarkSurfaceTint = Color(0xFFAFC9EB)
val DarkInverseSurface = Color(0xFFF9F9FE)
val DarkInverseOnSurface = Color(0xFF2E333A)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)
val DarkOutline = Color(0xFF71767E)
val DarkOutlineVariant = Color(0xFF434850)
val DarkScrim = Color(0xFF000000)
val DarkSurfaceBright = Color(0xFF272C33)
val DarkSurfaceDim = Color(0xFF0C0E12)
val DarkSurfaceContainer = Color(0xFF161A1F)
val DarkSurfaceContainerHigh = Color(0xFF1C2026)
val DarkSurfaceContainerHighest = Color(0xFF21262D)
val DarkSurfaceContainerLow = Color(0xFF101418)
val DarkSurfaceContainerLowest = Color(0xFF000000)
val DarkPrimaryFixed = Color(0xFFACCFFC)
val DarkPrimaryFixedDim = Color(0xFF9EC1ED)
val DarkOnPrimaryFixed = Color(0xFF053256)
val DarkOnPrimaryFixedVariant = Color(0xFF2B4F75)
val DarkSecondaryFixed = Color(0xFFD7E3F8)
val DarkSecondaryFixedDim = Color(0xFFC9D5E9)
val DarkOnSecondaryFixed = Color(0xFF344050)
val DarkOnSecondaryFixedVariant = Color(0xFF505C6D)
val DarkTertiaryFixed = Color(0xFFD5CBFC)
val DarkTertiaryFixedDim = Color(0xFFC7BEEE)
val DarkOnTertiaryFixed = Color(0xFF352F56)
val DarkOnTertiaryFixedVariant = Color(0xFF524B74)